export const tournaments = [
  {
    name: 'Legends Premier Trophy 2025',
    totalTeams: 5,
    playersPerTeam: 8,
    numOfOvers: 6,
    xOver: 3,
    otherSettings:
      '{"groups":["Group A","Group B","Group C","Group D","Group E","Group F","Group G","Group H"],"tShirtColors":[{"color 1":"#7c730d"},{"color 2":"#95dacb"},{"color 3":"#8800bc"},{"color 4":"#3b0def"},{"color 5":"#a964cf"}]}',
    teams: [
      {
        name: 'Mumbai Strikers',
        ownerName: 'Trace White',
        tShirtColor: '#7c730d',
      },
      {
        name: 'Delhi Warriors',
        ownerName: 'Jayson Leon',
        tShirtColor: '#95dacb',
      },
      {
        name: 'Chennai Titans',
        ownerName: 'Ariana Logan',
        tShirtColor: '#8800bc',
      },
      {
        name: 'Kolkata Hurricanes',
        ownerName: 'Eden Avila',
        tShirtColor: '#3b0def',
      },
      {
        name: 'Bangalore Blazers',
        ownerName: 'Kyson Christian',
        tShirtColor: '#95dacb',
      },
    ],
    players: [
      { name: 'Aarav Sharma', group: 'Group A', role: 'Batsman' },
      { name: 'Rohan Desai', group: 'Group A', role: 'All-Rounder' },
      { name: 'Kunal Iyer', group: 'Group A', role: 'Bowler' },
      { name: 'Aditya Reddy', group: 'Group A', role: 'Batsman' },
      { name: 'Nikhil Menon', group: 'Group A', role: 'All-Rounder' },
      { name: 'Suresh Patil', group: 'Group B', role: 'Batsman' },
      { name: 'Varun Kulkarni', group: 'Group B', role: 'Bowler' },
      { name: 'Devendra Prabhu', group: 'Group B', role: 'Batsman' },
      { name: 'Rajesh Nair', group: 'Group B', role: 'Batsman' },
      { name: 'Manish Malhotra', group: 'Group B', role: 'All-Rounder' },
      { name: 'Rohit Bansal', group: 'Group C', role: 'Bowler' },
      { name: 'Amit Tiwari', group: 'Group C', role: 'Batsman' },
      { name: 'Pranav Choudhary', group: 'Group C', role: 'Batsman' },
      { name: 'Yash Jadhav', group: 'Group C', role: 'All-Rounder' },
      { name: 'Ankit Saxena', group: 'Group C', role: 'Batsman' },
      { name: 'Kartik Verma', group: 'Group D', role: 'All-Rounder' },
      { name: 'Vivek Kapoor', group: 'Group D', role: 'Batsman' },
      { name: 'Piyush Sethi', group: 'Group D', role: 'Bowler' },
      { name: 'Harsh Vora', group: 'Group D', role: 'All-Rounder' },
      { name: 'Sameer Khan', group: 'Group D', role: 'Batsman' },
      { name: 'Arpit Doshi', group: 'Group E', role: 'Batsman' },
      { name: 'Hemit Doshi', group: 'Group E', role: 'All-Rounder' },
      { name: 'Tariq Hussain', group: 'Group E', role: 'All-Rounder' },
      { name: 'Aslam Mirza', group: 'Group E', role: 'Bowler' },
      { name: 'Farhan Pathan', group: 'Group E', role: 'Batsman' },
      { name: 'Arjun Joshi', group: 'Group F', role: 'All-Rounder' },
      { name: 'Siddharth Krishnan', group: 'Group F', role: 'Batsman' },
      { name: 'Rahul Pillai', group: 'Group F', role: 'Bowler' },
      { name: 'Naveen Rao', group: 'Group F', role: 'Batsman' },
      { name: 'Vikram Shetty', group: 'Group F', role: 'Bowler' },
      { name: 'Dhruv Shankar', group: 'Group G', role: 'Batsman' },
      { name: 'Sanjay Mehra', group: 'Group G', role: 'Batsman' },
      { name: 'Akash Trivedi', group: 'Group G', role: 'All-Rounder' },
      { name: 'Mohan Deshmukh', group: 'Group G', role: 'Bowler' },
      { name: 'Jayant Pawar', group: 'Group G', role: 'Batsman' },
      { name: 'Chirag Arora', group: 'Group H', role: 'All-Rounder' },
      { name: 'Sunil Ghosh', group: 'Group H', role: 'Batsman' },
      { name: 'Deepak Banerjee', group: 'Group H', role: 'All-Rounder' },
      { name: 'Abhishek Bose', group: 'Group H', role: 'Batsman' },
      { name: 'Keshav Mukherjee', group: 'Group H', role: 'Bowler' },
    ],
  },
]
