export const tournaments = [
  {
    name: 'Legends Premier Trophy 2025',
    teams: [
      { name: 'Mumbai Strikers' },
      { name: 'Delhi Warriors' },
      { name: 'Chennai Titans' },
      { name: 'Kolkata Hurricanes' },
      { name: 'Bangalore Blazers' },
    ],
    players: [
      { name: 'Aarav Sharma' },
      { name: 'Rohan Desai' },
      { name: 'Kunal Iyer' },
      { name: 'Aditya Reddy' },
      { name: 'Nikhil Menon' },
      { name: 'Suresh Patil' },
      { name: 'Varun Kulkarni' },
      { name: 'Devendra Prabhu' },
      { name: 'Rajesh Nair' },
      { name: 'Manish Malhotra' },
      { name: 'Rohit Bansal' },
      { name: 'Amit Tiwari' },
      { name: 'Pranav Choudhary' },
      { name: 'Yash Jadhav' },
      { name: 'Ankit Saxena' },
      { name: 'Kartik Verma' },
      { name: 'Vivek Kapoor' },
      { name: 'Piyush Sethi' },
      { name: 'Harsh Vora' },
      { name: 'Sameer Khan' },
      { name: 'Zaid Sheikh' },
      { name: 'Imran Qureshi' },
      { name: 'Tariq Hussain' },
      { name: 'Aslam Mirza' },
      { name: 'Farhan Pathan' },
      { name: 'Arjun Joshi' },
      { name: 'Siddharth Krishnan' },
      { name: 'Rahul Pillai' },
      { name: 'Naveen Rao' },
      { name: 'Vikram Shetty' },
      { name: 'Dhruv Shankar' },
      { name: 'Sanjay Mehra' },
      { name: 'Akash Trivedi' },
      { name: 'Mohan Deshmukh' },
      { name: 'Jayant Pawar' },
      { name: 'Chirag Arora' },
      { name: 'Sunil Ghosh' },
      { name: 'Deepak Banerjee' },
      { name: 'Abhishek Bose' },
      { name: 'Keshav Mukherjee' },
    ],
  },
]
