export const tournaments = [
  {
    name: 'SSDPL',
    teams: [
      { name: 'aptent' },
      { name: 'donec' },
      { name: 'scelerisque' },
      { name: 'dignissim' },
      { name: 'laoreet' },
    ],
    boards: [
      { name: 'Group H' },
      { name: 'Group G' },
      { name: 'Group F' },
      { name: 'Group E' },
      { name: 'Group D' },
      { name: 'Group C' },
      { name: 'Group B' },
      { name: 'Group A' },
    ],
    players: [
      { name: 'Lucas Mo' },
      { name: 'Xiaohua Lei' },
      { name: 'Raul O' },
      { name: 'Arun Romero' },
      { name: 'Ei Vo' },
      { name: 'Irina Ri' },
      { name: 'Vijay Jadhav' },
      { name: 'Alberto Lei' },
      { name: 'Henry Raut' },
      { name: 'Yue Ba' },
      { name: 'Ashok Ito' },
      { name: 'Richard Qiu' },
      { name: 'Liping Yin' },
      { name: 'Martha Taylor' },
      { name: 'Elizabeth Rojas' },
      { name: 'Peng Das' },
      { name: 'Alfred Patra' },
      { name: 'Nykolai Issa' },
      { name: 'Salma Souza' },
      { name: 'Hai Ji' },
      { name: 'Judith Yun' },
      { name: 'Sarah Kaur' },
      { name: 'Rong Andrade' },
      { name: 'Christine Juma' },
      { name: 'Qing Yılmaz' },
      { name: 'Richard Ceng' },
      { name: 'Mehmet Miah' },
      { name: 'Ruth Nayak' },
      { name: 'Mohan Kumari' },
      { name: 'Mohamed Rios' },
      { name: 'Adriana Prasad' },
      { name: 'Magdalena Santana' },
      { name: 'Jin Mejia' },
      { name: 'Henry Zhuang' },
      { name: 'Adam Ito' },
      { name: 'Lucia Qu' },
      { name: 'Rosa Chong' },
      { name: 'Natalya Dan' },
      { name: 'An Zhuang' },
      { name: 'Xiaofeng Herrera' },
    ],
  },
]
